### ISSUE TITLE
return value of opcache_get_status not checked

### ISSUE THREAD

**Issue by burkl** [janatzend/Z-Ray-OPcache#10]
´´´
<?php
opcache_reset();
?>
´´´

If you call this script while the extension is active, you will get:
"Warning: array_walk() expects parameter 1 to be array, null given in C:\Program Files (x86)\Zend\ZendServer\data\plugins\opcache\zray\OPcache.php on line 45"

This is because opcache_get_status can return false sometimes.

**Comment by janatzend** [comment]
fixed with 0a3ca23790a9411dd80caae4990c65cfc9889d56
